project:
  type: website

website:
  title: "ASI Summit"
  favicon: assets/logo.png
  search: false
  navbar:
    right:
      - text: Conduct
        href: conduct/index.qmd
      - location/index.qmd
      - registration/index.qmd
      - schedule/index.qmd
      - sponsors/index.qmd
      - about/index.qmd

format:
  html:
    theme:
      - solar
      - custom.scss
    css: styles.css
