project:
  type: website

website:
  title: "ASI Summit"
  favicon: assets/logo.png
  search: false
  navbar:
    right:
      - call-for-proposals/index.qmd
      - call-for-abstracts/index.qmd
      - location/index.qmd
      - registration/index.qmd
      - schedule/index.qmd
      - sponsors/index.qmd
      - about/index.qmd
      - text: Archive
        menu:
          - archive/2025/index.qmd
format:
  html:
    theme:
      - solar
      - custom.scss
    css: styles.css
